/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CuaHangRouteImport } from './routes/cua-hang'
import { Route as DangKyRouteImport } from './routes/dang-ky'
import { Route as DangNhapRouteImport } from './routes/dang-nhap'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GioHangRouteImport } from './routes/gio-hang'
import { Route as GioiThieuRouteImport } from './routes/gioi-thieu'
import { Route as HuongDanChonSizeRouteImport } from './routes/huong-dan-chon-size'
import { Route as LienHeRouteImport } from './routes/lien-he'
import { Route as LookbookRouteImport } from './routes/lookbook'
import { Route as TaiKhoanRouteImport } from './routes/tai-khoan'
import { Route as ThanhToanRouteImport } from './routes/thanh-toan'
import { Route as TimKiemRouteImport } from './routes/tim-kiem'
import { Route as YeuThichRouteImport } from './routes/yeu-thich'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BoSuuTapIndexRouteImport } from './routes/bo-suu-tap.index'
import { Route as BoSuuTapSlugRouteImport } from './routes/bo-suu-tap.$slug'
import { Route as ChinhSachSlugRouteImport } from './routes/chinh-sach.$slug'
import { Route as DanhMucSlugRouteImport } from './routes/danh-muc.$slug'
import { Route as SanPhamSlugRouteImport } from './routes/san-pham.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CuaHangRoute = CuaHangRouteImport.update({
  id: '/cua-hang',
  path: '/cua-hang',
  getParentRoute: () => rootRouteImport,
} as any)
const DangKyRoute = DangKyRouteImport.update({
  id: '/dang-ky',
  path: '/dang-ky',
  getParentRoute: () => rootRouteImport,
} as any)
const DangNhapRoute = DangNhapRouteImport.update({
  id: '/dang-nhap',
  path: '/dang-nhap',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GioHangRoute = GioHangRouteImport.update({
  id: '/gio-hang',
  path: '/gio-hang',
  getParentRoute: () => rootRouteImport,
} as any)
const GioiThieuRoute = GioiThieuRouteImport.update({
  id: '/gioi-thieu',
  path: '/gioi-thieu',
  getParentRoute: () => rootRouteImport,
} as any)
const HuongDanChonSizeRoute = HuongDanChonSizeRouteImport.update({
  id: '/huong-dan-chon-size',
  path: '/huong-dan-chon-size',
  getParentRoute: () => rootRouteImport,
} as any)
const LienHeRoute = LienHeRouteImport.update({
  id: '/lien-he',
  path: '/lien-he',
  getParentRoute: () => rootRouteImport,
} as any)
const LookbookRoute = LookbookRouteImport.update({
  id: '/lookbook',
  path: '/lookbook',
  getParentRoute: () => rootRouteImport,
} as any)
const TaiKhoanRoute = TaiKhoanRouteImport.update({
  id: '/tai-khoan',
  path: '/tai-khoan',
  getParentRoute: () => rootRouteImport,
} as any)
const ThanhToanRoute = ThanhToanRouteImport.update({
  id: '/thanh-toan',
  path: '/thanh-toan',
  getParentRoute: () => rootRouteImport,
} as any)
const TimKiemRoute = TimKiemRouteImport.update({
  id: '/tim-kiem',
  path: '/tim-kiem',
  getParentRoute: () => rootRouteImport,
} as any)
const YeuThichRoute = YeuThichRouteImport.update({
  id: '/yeu-thich',
  path: '/yeu-thich',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BoSuuTapIndexRoute = BoSuuTapIndexRouteImport.update({
  id: '/bo-suu-tap/',
  path: '/bo-suu-tap/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoSuuTapSlugRoute = BoSuuTapSlugRouteImport.update({
  id: '/bo-suu-tap/$slug',
  path: '/bo-suu-tap/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ChinhSachSlugRoute = ChinhSachSlugRouteImport.update({
  id: '/chinh-sach/$slug',
  path: '/chinh-sach/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DanhMucSlugRoute = DanhMucSlugRouteImport.update({
  id: '/danh-muc/$slug',
  path: '/danh-muc/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SanPhamSlugRoute = SanPhamSlugRouteImport.update({
  id: '/san-pham/$slug',
  path: '/san-pham/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cua-hang': typeof CuaHangRoute
  '/dang-ky': typeof DangKyRoute
  '/dang-nhap': typeof DangNhapRoute
  '/faq': typeof FaqRoute
  '/gio-hang': typeof GioHangRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/huong-dan-chon-size': typeof HuongDanChonSizeRoute
  '/lien-he': typeof LienHeRoute
  '/lookbook': typeof LookbookRoute
  '/tai-khoan': typeof TaiKhoanRoute
  '/thanh-toan': typeof ThanhToanRoute
  '/tim-kiem': typeof TimKiemRoute
  '/yeu-thich': typeof YeuThichRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/bo-suu-tap/$slug': typeof BoSuuTapSlugRoute
  '/chinh-sach/$slug': typeof ChinhSachSlugRoute
  '/danh-muc/$slug': typeof DanhMucSlugRoute
  '/san-pham/$slug': typeof SanPhamSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/bo-suu-tap/': typeof BoSuuTapIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cua-hang': typeof CuaHangRoute
  '/dang-ky': typeof DangKyRoute
  '/dang-nhap': typeof DangNhapRoute
  '/faq': typeof FaqRoute
  '/gio-hang': typeof GioHangRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/huong-dan-chon-size': typeof HuongDanChonSizeRoute
  '/lien-he': typeof LienHeRoute
  '/lookbook': typeof LookbookRoute
  '/tai-khoan': typeof TaiKhoanRoute
  '/thanh-toan': typeof ThanhToanRoute
  '/tim-kiem': typeof TimKiemRoute
  '/yeu-thich': typeof YeuThichRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/bo-suu-tap/$slug': typeof BoSuuTapSlugRoute
  '/chinh-sach/$slug': typeof ChinhSachSlugRoute
  '/danh-muc/$slug': typeof DanhMucSlugRoute
  '/san-pham/$slug': typeof SanPhamSlugRoute
  '/blog': typeof BlogIndexRoute
  '/bo-suu-tap': typeof BoSuuTapIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cua-hang': typeof CuaHangRoute
  '/dang-ky': typeof DangKyRoute
  '/dang-nhap': typeof DangNhapRoute
  '/faq': typeof FaqRoute
  '/gio-hang': typeof GioHangRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/huong-dan-chon-size': typeof HuongDanChonSizeRoute
  '/lien-he': typeof LienHeRoute
  '/lookbook': typeof LookbookRoute
  '/tai-khoan': typeof TaiKhoanRoute
  '/thanh-toan': typeof ThanhToanRoute
  '/tim-kiem': typeof TimKiemRoute
  '/yeu-thich': typeof YeuThichRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/bo-suu-tap/$slug': typeof BoSuuTapSlugRoute
  '/chinh-sach/$slug': typeof ChinhSachSlugRoute
  '/danh-muc/$slug': typeof DanhMucSlugRoute
  '/san-pham/$slug': typeof SanPhamSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/bo-suu-tap/': typeof BoSuuTapIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cua-hang'
    | '/dang-ky'
    | '/dang-nhap'
    | '/faq'
    | '/gio-hang'
    | '/gioi-thieu'
    | '/huong-dan-chon-size'
    | '/lien-he'
    | '/lookbook'
    | '/tai-khoan'
    | '/thanh-toan'
    | '/tim-kiem'
    | '/yeu-thich'
    | '/blog/$slug'
    | '/bo-suu-tap/$slug'
    | '/chinh-sach/$slug'
    | '/danh-muc/$slug'
    | '/san-pham/$slug'
    | '/blog/'
    | '/bo-suu-tap/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cua-hang'
    | '/dang-ky'
    | '/dang-nhap'
    | '/faq'
    | '/gio-hang'
    | '/gioi-thieu'
    | '/huong-dan-chon-size'
    | '/lien-he'
    | '/lookbook'
    | '/tai-khoan'
    | '/thanh-toan'
    | '/tim-kiem'
    | '/yeu-thich'
    | '/blog/$slug'
    | '/bo-suu-tap/$slug'
    | '/chinh-sach/$slug'
    | '/danh-muc/$slug'
    | '/san-pham/$slug'
    | '/blog'
    | '/bo-suu-tap'
  id:
    | '__root__'
    | '/'
    | '/cua-hang'
    | '/dang-ky'
    | '/dang-nhap'
    | '/faq'
    | '/gio-hang'
    | '/gioi-thieu'
    | '/huong-dan-chon-size'
    | '/lien-he'
    | '/lookbook'
    | '/tai-khoan'
    | '/thanh-toan'
    | '/tim-kiem'
    | '/yeu-thich'
    | '/blog/$slug'
    | '/bo-suu-tap/$slug'
    | '/chinh-sach/$slug'
    | '/danh-muc/$slug'
    | '/san-pham/$slug'
    | '/blog/'
    | '/bo-suu-tap/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CuaHangRoute: typeof CuaHangRoute
  DangKyRoute: typeof DangKyRoute
  DangNhapRoute: typeof DangNhapRoute
  FaqRoute: typeof FaqRoute
  GioHangRoute: typeof GioHangRoute
  GioiThieuRoute: typeof GioiThieuRoute
  HuongDanChonSizeRoute: typeof HuongDanChonSizeRoute
  LienHeRoute: typeof LienHeRoute
  LookbookRoute: typeof LookbookRoute
  TaiKhoanRoute: typeof TaiKhoanRoute
  ThanhToanRoute: typeof ThanhToanRoute
  TimKiemRoute: typeof TimKiemRoute
  YeuThichRoute: typeof YeuThichRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BoSuuTapSlugRoute: typeof BoSuuTapSlugRoute
  ChinhSachSlugRoute: typeof ChinhSachSlugRoute
  DanhMucSlugRoute: typeof DanhMucSlugRoute
  SanPhamSlugRoute: typeof SanPhamSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  BoSuuTapIndexRoute: typeof BoSuuTapIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cua-hang': {
      id: '/cua-hang'
      path: '/cua-hang'
      fullPath: '/cua-hang'
      preLoaderRoute: typeof CuaHangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dang-ky': {
      id: '/dang-ky'
      path: '/dang-ky'
      fullPath: '/dang-ky'
      preLoaderRoute: typeof DangKyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dang-nhap': {
      id: '/dang-nhap'
      path: '/dang-nhap'
      fullPath: '/dang-nhap'
      preLoaderRoute: typeof DangNhapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gio-hang': {
      id: '/gio-hang'
      path: '/gio-hang'
      fullPath: '/gio-hang'
      preLoaderRoute: typeof GioHangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gioi-thieu': {
      id: '/gioi-thieu'
      path: '/gioi-thieu'
      fullPath: '/gioi-thieu'
      preLoaderRoute: typeof GioiThieuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/huong-dan-chon-size': {
      id: '/huong-dan-chon-size'
      path: '/huong-dan-chon-size'
      fullPath: '/huong-dan-chon-size'
      preLoaderRoute: typeof HuongDanChonSizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lien-he': {
      id: '/lien-he'
      path: '/lien-he'
      fullPath: '/lien-he'
      preLoaderRoute: typeof LienHeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookbook': {
      id: '/lookbook'
      path: '/lookbook'
      fullPath: '/lookbook'
      preLoaderRoute: typeof LookbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tai-khoan': {
      id: '/tai-khoan'
      path: '/tai-khoan'
      fullPath: '/tai-khoan'
      preLoaderRoute: typeof TaiKhoanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thanh-toan': {
      id: '/thanh-toan'
      path: '/thanh-toan'
      fullPath: '/thanh-toan'
      preLoaderRoute: typeof ThanhToanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tim-kiem': {
      id: '/tim-kiem'
      path: '/tim-kiem'
      fullPath: '/tim-kiem'
      preLoaderRoute: typeof TimKiemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yeu-thich': {
      id: '/yeu-thich'
      path: '/yeu-thich'
      fullPath: '/yeu-thich'
      preLoaderRoute: typeof YeuThichRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bo-suu-tap/': {
      id: '/bo-suu-tap/'
      path: '/bo-suu-tap'
      fullPath: '/bo-suu-tap/'
      preLoaderRoute: typeof BoSuuTapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bo-suu-tap/$slug': {
      id: '/bo-suu-tap/$slug'
      path: '/bo-suu-tap/$slug'
      fullPath: '/bo-suu-tap/$slug'
      preLoaderRoute: typeof BoSuuTapSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chinh-sach/$slug': {
      id: '/chinh-sach/$slug'
      path: '/chinh-sach/$slug'
      fullPath: '/chinh-sach/$slug'
      preLoaderRoute: typeof ChinhSachSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/danh-muc/$slug': {
      id: '/danh-muc/$slug'
      path: '/danh-muc/$slug'
      fullPath: '/danh-muc/$slug'
      preLoaderRoute: typeof DanhMucSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/san-pham/$slug': {
      id: '/san-pham/$slug'
      path: '/san-pham/$slug'
      fullPath: '/san-pham/$slug'
      preLoaderRoute: typeof SanPhamSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CuaHangRoute: CuaHangRoute,
  DangKyRoute: DangKyRoute,
  DangNhapRoute: DangNhapRoute,
  FaqRoute: FaqRoute,
  GioHangRoute: GioHangRoute,
  GioiThieuRoute: GioiThieuRoute,
  HuongDanChonSizeRoute: HuongDanChonSizeRoute,
  LienHeRoute: LienHeRoute,
  LookbookRoute: LookbookRoute,
  TaiKhoanRoute: TaiKhoanRoute,
  ThanhToanRoute: ThanhToanRoute,
  TimKiemRoute: TimKiemRoute,
  YeuThichRoute: YeuThichRoute,
  BlogSlugRoute: BlogSlugRoute,
  BoSuuTapSlugRoute: BoSuuTapSlugRoute,
  ChinhSachSlugRoute: ChinhSachSlugRoute,
  DanhMucSlugRoute: DanhMucSlugRoute,
  SanPhamSlugRoute: SanPhamSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  BoSuuTapIndexRoute: BoSuuTapIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
